
clusterName: production-eks

region: ap-south-1

vpcId: vpc-09c126c4b9ddf5d39

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::028987315631:role/aws-load-balancer-controller-role

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

replicaCount: 2

extraArgs:
  - --aws-max-retries=10
