apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-external-secret
  namespace: payment
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: payment-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: payment-service-secret
        property: DB_HOST
    - secretKey: DB_USER
      remoteRef:
        key: payment-service-secret
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: payment-service-secret
        property: DB_PASSWORD
