apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service-sa
  namespace: payment
  annotations:
    # IRSA annotation: links this ServiceAccount to the AWS IAM Role.
    # The EKS Pod Identity Webhook injects AWS_ROLE_ARN and
    # AWS_WEB_IDENTITY_TOKEN_FILE into every pod that uses this SA.
    eks.amazonaws.com/role-arn: arn:aws:iam::028987315631:role/payment-service-irsa-role
