apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: exercise24
  labels:
    app: customer-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: customer-app
