apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: troubleshooting-lab-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Manikandan23005/Devops-Exercise.git'
    targetRevision: HEAD
    path: Exercise-23/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: exercise-23
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
