apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: exercise-4
spec:
  refreshInterval: 1m

  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: db-secret

  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: exercise4-db-secret
      property: password