apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-prod
  namespace: argocd
  labels:
    environment: prod
    app: python-app
spec:
  project: default
  source:
    repoURL: https://github.com/Manikandan23005/Devops-Exercise.git
    targetRevision: main
    path: Exercise-18/helm-chart
    helm:
      valueFiles:
        - ../gitops/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
