apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-qa
  namespace: argocd
  labels:
    environment: qa
    app: python-app
spec:
  project: default
  source:
    repoURL: https://github.com/Manikandan23005/Devops-Exercise.git
    targetRevision: main
    path: Exercise-18/helm-chart
    helm:
      valueFiles:
        - ../gitops/qa/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
